### ISSUE TITLE
The model folder not contains STCGNN module?

### ISSUE THREAD

**Issue by Yonoi** [znwang918/CitySiren#1]
Hello Wang:
Recently, i read your paper "Spatio-Temporal-Categorical Graph Neural Networks for Fine-Grained Multi-incident Co-Prediction", and think that's an excellent work. So i want to reconstruct this model in your paper, but i can't find any related code of your model in this repo.

**Comment by underdoc-wang** [comment]
Thank you so much for your interest on our paper. Appreciate it!
Also, I'm sorry for not updating this repo on time. I'll upload the code and data soon in December. I'll let you know as soon as I do it.

**Comment by Yonoi** [comment]
Ok, thank you so much. I'm looking forward to it.

**Comment by underdoc-wang** [comment]
Hi, the code and sample data have been uploaded to the repo. Please check it out! Again, thanks for your interest!

**Comment by Yonoi** [comment]
Awesome！thank you so much.



---- 回复的原邮件 ----
| 发件人 | Zhaonan ***@***.***> |
| 日期 | 2021年12月29日 17:38 |
| 收件人 | ***@***.***> |
| 抄送至 | Sun ***@***.******@***.***> |
| 主题 | Re: [underdoc-wang/STC-GNN] The model folder not contains STCGNN module? (Issue #1) |

Hi, the code and sample data have been uploaded to the repo. Please check it out! Again, thanks for your interest!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
